version: "3.9"

services:
  db:
    image: postgres:14
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./backend/migrations:/docker-entrypoint-initdb.d

  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    env_file:
      - ./.env
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
